FROM nvcr.io/nvidia/tensorflow:23.11-tf2-py3
ARG workdir_path=/tmp
WORKDIR $workdir_path

# Env variables
ENV DL_BACKEND=TENSORFLOW

# Install pip requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt

WORKDIR /
CMD [ "bash" ]