FROM nvcr.io/nvidia/pytorch:23.11-py3
ARG workdir_path=/tmp
WORKDIR $workdir_path

# Env variables
ENV DL_BACKEND=PYTORCH

# Install pip requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt

WORKDIR /
CMD [ "bash" ]