name: Call documentation build & deploy
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-docs-build-and-deploy:
    uses: OndrejSzekely/metron_ai_deepforge/.github/workflows/base_build_and_deploy_docs.yml@main
    with:
      deploy_docs: true
