name: Rebuild DeepForge PyTorch Docker image in ACR
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-change:
    runs-on: ubuntu-latest
    outputs:
      project_requirements: ${{ steps.code_check.outputs.project_requirements }}
    steps:
      - name: Checkout DeepForge repo
        uses: actions/checkout@v4
      - name: Check code change
        id: code_check
        uses: dorny/paths-filter@v3
        with:
          filters: |
            project_requirements:
              - 'Dockerfile.pytorch'
              - 'pyproject.toml'
  build-image:
    needs: check-code-change
    if: ${{ needs.check-code-change.outputs.project_requirements == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DeepForge repo
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      - name: Rebuild Docker image
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --registry ${{ vars.ACR_REGISTRY }} --image metron_ai/deepforge_pt:latest --file Dockerfile.pytorch .
  skip-workflow:
    needs: check-code-change
    if: ${{ needs.check-code-change.outputs.project_requirements == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skipping Action
        run: echo "Action is skipped"