name: Rebuild DeepForge PyTorch Docker image for ACR
on:
  push:
    branches: ["main"]
    paths:
      - Dockerfile.pytorch
      - pyproject.toml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "images"
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DeepForge repo
        uses: actions/checkout@v4
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_URL }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      - name: Build & push Docker image
        run: |
          docker build -t ${{ vars.ACR_URL }}/metron_ai/deepforge_pt -f Dockerfile.pytorch .
          docker push ${{ vars.ACR_URL }}/metron_ai/deepforge_pt:latest

      