name: Rebuild DeepForge PyTorch Docker image in ACR
on:
  push:
    branches: ["main"]
    paths:
      - Dockerfile.pytorch
      - pyproject.toml
  pull_request:
    branches: ["main"]
    paths:
      - Dockerfile.pytorch
      - pyproject.toml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: "images"
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DeepForge repo
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      - name: Rebuild Docker image
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build --registry ${{ vars.ACR_REGISTRY }} --image metron_ai/deepforge_pt:latest --file Dockerfile.pytorch .