name: Set up DeepForge CPU Environment
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cpu-env-setup-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout DeepForge repo
          uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"
        - name: Set up Python
          run: uv venv
        - name: Install PyTorch for CPU
          run: uv pip install --requirements .github/pytorch_cpu_runner_requirements.txt
        - name: Install project dependencies
          run: uv sync --group devtools --all-extras --inexact --frozen
        - name: Minimize uv cache
          run: uv cache prune --ci